### ISSUE TITLE
Convert px to numbers fails when overriding previous property

### ISSUE THREAD

**Issue by alexmick** [sabeurthabti/react-native-css#26]
This css

```css
.row {
  padding: 10px;
  padding-left: 5px;
  flex-direction: row;
  margin-bottom: 2px;
}
```

will compile to

```js
row: {
  paddingTop: 10,
  paddingBottom: 10,
  paddingRight: 10,
  paddingLeft: "5px",
  flexDirection: row,
  marginBottom: "2px",
}
```

which is not valid for a React Native Stylesheet.

I believe this is because the `padding-left` overrides the `padding` just above and that isn't properly managed.

I've forked the repo, written a regression test and will try to submit a PR with a fix.
