### ISSUE TITLE
value auto is set like null

### ISSUE THREAD

**Issue by juvasquezg** [sabeurthabti/react-native-css#37]
Hi,

When I use the property with 'auto', it set like null ¿it is normal?

for example:

```css
img {
  width: 100%;
  height: auto;
}
```

Generate

```css
"img":{"width":100,"height":null}
```

Thank you!!
